# Generated by Django 5.2.1 on 2025-05-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_place_alcohol_remove_place_baby_sit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='expectations',
        ),
        migrations.RemoveField(
            model_name='place',
            name='tags',
        ),
        migrations.AddField(
            model_name='place',
            name='alcohol',
            field=models.BooleanField(default=False, verbose_name='Alcohol'),
        ),
        migrations.AddField(
            model_name='place',
            name='baby_sit',
            field=models.BooleanField(default=False, verbose_name='Baby Sitting'),
        ),
        migrations.AddField(
            model_name='place',
            name='bar',
            field=models.BooleanField(default=False, verbose_name='Bar'),
        ),
        migrations.AddField(
            model_name='place',
            name='beach',
            field=models.BooleanField(default=False, verbose_name='Beach'),
        ),
        migrations.AddField(
            model_name='place',
            name='cash',
            field=models.BooleanField(default=False, verbose_name='Cash Payment'),
        ),
        migrations.AddField(
            model_name='place',
            name='castles',
            field=models.BooleanField(default=False, verbose_name='Castle'),
        ),
        migrations.AddField(
            model_name='place',
            name='coffee',
            field=models.BooleanField(default=False, verbose_name='Coffee'),
        ),
        migrations.AddField(
            model_name='place',
            name='creative_places',
            field=models.BooleanField(default=False, verbose_name='Creative Place'),
        ),
        migrations.AddField(
            model_name='place',
            name='dessert',
            field=models.BooleanField(default=False, verbose_name='Dessert'),
        ),
        migrations.AddField(
            model_name='place',
            name='famagusta',
            field=models.BooleanField(default=False, verbose_name='Famagusta'),
        ),
        migrations.AddField(
            model_name='place',
            name='fish',
            field=models.BooleanField(default=False, verbose_name='Fish'),
        ),
        migrations.AddField(
            model_name='place',
            name='free_park_area',
            field=models.BooleanField(default=False, verbose_name='Free Parking Area'),
        ),
        migrations.AddField(
            model_name='place',
            name='guzelyurt',
            field=models.BooleanField(default=False, verbose_name='Guzelyurt'),
        ),
        migrations.AddField(
            model_name='place',
            name='hiking_trails',
            field=models.BooleanField(default=False, verbose_name='Hiking trails'),
        ),
        migrations.AddField(
            model_name='place',
            name='historical_places',
            field=models.BooleanField(default=False, verbose_name='Historical Places'),
        ),
        migrations.AddField(
            model_name='place',
            name='inside_area',
            field=models.BooleanField(default=False, verbose_name='Inside Area'),
        ),
        migrations.AddField(
            model_name='place',
            name='iskele',
            field=models.BooleanField(default=False, verbose_name='Iskele'),
        ),
        migrations.AddField(
            model_name='place',
            name='kard_pay',
            field=models.BooleanField(default=False, verbose_name='Card Payment'),
        ),
        migrations.AddField(
            model_name='place',
            name='karpaz',
            field=models.BooleanField(default=False, verbose_name='Karpaz'),
        ),
        migrations.AddField(
            model_name='place',
            name='kids_menu',
            field=models.BooleanField(default=False, verbose_name='Kids Menu'),
        ),
        migrations.AddField(
            model_name='place',
            name='kitchen',
            field=models.BooleanField(default=False, verbose_name='Kitchen'),
        ),
        migrations.AddField(
            model_name='place',
            name='kyrenia',
            field=models.BooleanField(default=False, verbose_name='Kyrenia'),
        ),
        migrations.AddField(
            model_name='place',
            name='lefke',
            field=models.BooleanField(default=False, verbose_name='Lefke'),
        ),
        migrations.AddField(
            model_name='place',
            name='meat_and_chicken',
            field=models.BooleanField(default=False, verbose_name='Meat/Chicken'),
        ),
        migrations.AddField(
            model_name='place',
            name='museum',
            field=models.BooleanField(default=False, verbose_name='Museum'),
        ),
        migrations.AddField(
            model_name='place',
            name='nicosia',
            field=models.BooleanField(default=False, verbose_name='Nicosia'),
        ),
        migrations.AddField(
            model_name='place',
            name='outside_area',
            field=models.BooleanField(default=False, verbose_name='Outside Area'),
        ),
        migrations.AddField(
            model_name='place',
            name='parks',
            field=models.BooleanField(default=False, verbose_name='Parks'),
        ),
        migrations.AddField(
            model_name='place',
            name='pets_allow',
            field=models.BooleanField(default=False, verbose_name='Pets Allow'),
        ),
        migrations.AddField(
            model_name='place',
            name='popular',
            field=models.BooleanField(default=False, verbose_name='Popular'),
        ),
        migrations.AddField(
            model_name='place',
            name='reservation',
            field=models.BooleanField(default=False, verbose_name='Reservation Taken'),
        ),
        migrations.AddField(
            model_name='place',
            name='waterfalls',
            field=models.BooleanField(default=False, verbose_name='Waterfalls'),
        ),
        migrations.AddField(
            model_name='place',
            name='wheelchair_accessible_entrance',
            field=models.BooleanField(default=False, verbose_name='Wheelchair Accessible'),
        ),
    ]
